### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by nannione** [digedag/t3users#1]
Hello, 
after inserting the extension i receive the error
`Fatal error: Class 'tx_rnbase_filter_BaseFilter' not found in /.../typo3conf/ext/t3users/actions/class.tx_t3users_actions_ListFeUsers.php on line 106`
I use typo3 6.2.19 .

**Comment by digedag** [comment]
Can you try it again? I added an include...

**Comment by digedag** [comment]
Should work now!
