### ISSUE TITLE
BE-Modul wird nicht geladen

### ISSUE THREAD

**Issue by digedag** [digedag/t3users#6]
Das "zweite" BE-Modul **Web->FE User** bricht in TYPO3 6.2 mit einem PHP Fehler ab:

```
PHP Fatal error:  Class 'tx_mklib_util_TCA' not found in /typo3conf/ext/t3users/mod/decorator/class.tx_t3users_mod_decorator_Base.php on line 130
```

Da t3users keine Referenz zu mklib haben sollte, muss dieser Aufruf entfernt werden. Eine TCA-Util Klasse gibt es auch in rn_base.

**Comment by hannesbochmann** [comment]
Ich kümmere mich darum.

**Comment by digedag** [comment]
Gerne! Wobei ich immer noch nicht genau weiß, was dieses Modul anders macht, als das Sub-Modul unter **Web->Funktionen**... :smile:

**Comment by hannesbochmann** [comment]
Ich auch nicht. Habs auch noch nie in Verwendung gesehen. Ich würde auch ehrlich gesagt dazu tendieren dieses Modul zu entfernen. Was sagst du dazu?

**Comment by digedag** [comment]
Rede vorher mal mit Thomas. Der hat es damals eingebaut...
