### ISSUE TITLE
Zielseite nach Login per FE-Group konfigurieren

### ISSUE THREAD

**Issue by digedag** [digedag/t3users#7]
Die Extension felogin erweitert die GR-Gruppen um das Attribut **Bei Anmeldung zur folgenden Seite weiterleiten**. Das sollte von T3users ebenfalls unterstützt werden.

**Comment by hannesbochmann** [comment]
Vielleicht sollte mal noch geprüft werden ob das Login mit t3users überhaupt noch Sinn macht oder nicht doch felogin genutzt werden sollte.

**Comment by digedag** [comment]
Ich bin mit t3users zufrieden. Da sind alle notwendigen Hooks drin. Und ich kann mich darauf verlassen, daß es immer funktioniert. Bei felogin weiß ich das nicht...
